SELECT * FROM V$VERSION;

-- 테이블
CREATE TABLE MEMBER(
    mno         NUMBER(6),
    memail      VARCHAR2(50) NOT NULL,
    mpasswd     VARCHAR2(200) NOT NULL,
    mname       VARCHAR2(30) NOT NULL,
    maddr       VARCHAR2(200) NOT NULL,
    mtel        VARCHAR2(15) NOT NULL,
    maccount    VARCHAR2(200) NOT NULL,
    mgrade      VARCHAR2(20) DEFAULT '일반회원',
    mdate       DATE DEFAULT SYSDATE,
    mpoint      NUMBER(6) DEFAULT 0,
    
    CONSTRAINT PK_MEMBER PRIMARY KEY(mno)
);

DESC MEMBER;

INSERT INTO MEMBER(MNO,MEMAIL,MPASSWD,MNAME,MADDR,MTEL,MACCOUNT,MGRADE,MDATE,MPOINT)
 VALUES(MEMBER_SEQ.NEXTVAL,'qwer@qwer.com','1234','admin','주소','010-1234-1234','계좌','ADMIN',SYSDATE,0);
INSERT INTO MEMBER(MNO,MEMAIL,MPASSWD,MNAME,MADDR,MTEL,MACCOUNT,MGRADE,MDATE,MPOINT)
 VALUES(MEMBER_SEQ.NEXTVAL,'asdf@asdf.com','1234','member1','주소','010-5678-5678','계좌','NORMAL',SYSDATE,0);
 
UPDATE MEMBER
 SET MPASSWD = '$2a$10$TgQJV.CwIcL8FplT5fhZ5OpG08nfL48aQ7DTETDx0dFYmN/.TcoKO'
 WHERE MNO = 1
    OR MNO = 2;
    
UPDATE MEMBER
 SET MGRADE = 'ADMIN'
 WHERE MNO = 1;
UPDATE MEMBER
 SET MGRADE = 'NORMAL'
 WHERE MNO = 2;
UPDATE MEMBER
 SET MNAME = 'member2'
 WHERE MNO = 3; 
UPDATE MEMBER
 SET MTEL = '010-4184-3662'
 WHERE MNO = 21;

UPDATE MEMBER
   SET MEMAIL = 'admin'
 WHERE MNO = 1;

SELECT * FROM MEMBER;

CREATE TABLE QNA(
    qno         NUMBER(6),
    qtitle      VARCHAR2(50) NOT NULL,
    qcontent    VARCHAR2(1000) NOT NULL,
    qfiles      VARCHAR2(1000),
    qpasswd     VARCHAR2(200) NOT NULL,
    qsecret     VARCHAR2(10) DEFAULT '비밀글',
    qdate       DATE DEFAULT SYSDATE,
    qhit        NUMBER(10) DEFAULT 0,
    mno         NUMBER(6),
    
    CONSTRAINT PK_QNA PRIMARY KEY(qno),
    CONSTRAINT FK_QNA_MEMBER 
     FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE
);
SELECT * FROM QNA;
CREATE TABLE ADMIN_BOARD(
    abno        NUMBER(6),
    abtitle     VARCHAR2(50) NOT NULL,
    abcontent   VARCHAR2(300),
    abfiles     VARCHAR2(1000),
    abdate      DATE DEFAULT SYSDATE,
    abhit       NUMBER(10) DEFAULT 0,
    abcategory  VARCHAR2(15) NOT NULL,
    mno         NUMBER(6),
    
    CONSTRAINT PK_AB PRIMARY KEY(abno),
    CONSTRAINT FK_AB_MEMBER 
     FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE
);

CREATE TABLE RATING(
    rno         NUMBER(6),
    rrate       NUMBER(2,1) NOT NULL,
    rtitle      VARCHAR2(50) NOT NULL,
    rcontent    VARCHAR2(1000),
    rfiles      VARCHAR2(1000),
    rdate       DATE DEFAULT SYSDATE,
    rhit        NUMBER(10) DEFAULT 0,
    mno         NUMBER(6),
    bno         NUMBER(6),
    odno        NUMBER(6),
    
    CONSTRAINT PK_RATING PRIMARY KEY(rno),
    CONSTRAINT FK_RATING_MEMBER 
     FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_BOOK 
     FOREIGN KEY(bno) REFERENCES BOOK(bno) ON DELETE CASCADE,
    CONSTRAINT FK_RATING_OD 
     FOREIGN KEY(odno) REFERENCES ORDER_DETAIL(odno) ON DELETE CASCADE
);

SELECT * FROM RATING;

ALTER TABLE QNA MODIFY QCONTENT VARCHAR2(1000);
ALTER TABLE RATING MODIFY RCONTENT VARCHAR2(1000);

CREATE TABLE BOOK(
    bno         NUMBER(6),
    bname       VARCHAR2(1000) NOT NULL,
    bprice      NUMBER(6) NOT NULL,
    bage        VARCHAR2(20) NOT NULL,
    bgenre      VARCHAR2(20) NOT NULL,
    bpublisher  VARCHAR2(20) NOT NULL,
    bimg        VARCHAR2(1000) NOT NULL,
    binfo       VARCHAR2(1000) NOT NULL,
    bstock      NUMBER(5) NOT NULL,
    blike       NUMBER(4) DEFAULT 0,
    
    CONSTRAINT PK_BOOK PRIMARY KEY(bno)
);

-- DELETE FROM BOOK;
SELECT * FROM BOOK ORDER BY BNO;
SELECT * FROM BOOK ORDER BY BLIKE;
DESC BOOK;

SELECT *
  FROM BOOK;

SELECT COUNT(*)
  FROM (SELECT BNAME
          FROM BOOK
         GROUP BY BNAME
        HAVING COUNT(*) > 1);

ALTER TABLE BOOK MODIFY BNAME VARCHAR2(1000);
ALTER TABLE BOOK MODIFY BIMG VARCHAR2(1000);

UPDATE BOOK
   SET BINFO = '//gndrbook.com/web/upload/NNEditor/20260210/ED9484EBA2B0EBB2A8_EC82BCEAB5ADECA780_30.png'
 WHERE BNO = 100001;

UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100619;
UPDATE BOOK SET BLIKE = 27 WHERE BNO = 100634;
UPDATE BOOK SET BLIKE = 25 WHERE BNO = 100662;
UPDATE BOOK SET BLIKE = 23 WHERE BNO = 100688;
UPDATE BOOK SET BLIKE = 2 WHERE BNO = 100701;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100773;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100789;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100804;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100818;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100829;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100845;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100862;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100878;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100903;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100936;
UPDATE BOOK SET BLIKE = 30 WHERE BNO = 100965;
 


CREATE TABLE PASS(
    pno         NUMBER(6),
    pname       VARCHAR2(30) NOT NULL,
    pprice      NUMBER(6) NOT NULL,
    ptype       VARCHAR2(15) NOT NULL,
    pperiod     NUMBER(3),
    pcount      NUMBER(3),
    pimg        VARCHAR2(400) NOT NULL,
    pinfo       VARCHAR2(400) NOT NULL,
    
    CONSTRAINT PK_PASS PRIMARY KEY(pno)
);

SELECT * FROM PASS;

UPDATE PASS
 SET PNO = 900001
 WHERE PNO = 900002; 
UPDATE PASS
 SET PINFO = '//gndrbook.com/web/upload/NNEditor/20250527/copy-1748331281-3_gif.gif'
 WHERE PNO = 900001;  


ALTER TABLE PASS
  ADD pimg VARCHAR2(400) NOT NULL;
DESC PASS;

SELECT * FROM PASS;

CREATE TABLE CART(
    cno         NUMBER(6),
    ctype       VARCHAR2(10) NOT NULL,
    cstock      NUMBER(2) NOT NULL,
    mno         NUMBER(6),
    bno         NUMBER(6),
    pno         NUMBER(6),
    
    CONSTRAINT PK_CART PRIMARY KEY(cno),
    CONSTRAINT FK_CART_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_CART_BOOK 
        FOREIGN KEY(bno) REFERENCES BOOK(bno) ON DELETE CASCADE,
    CONSTRAINT FK_CART_PASS 
        FOREIGN KEY(pno) REFERENCES PASS(pno) ON DELETE CASCADE
);

SELECT * FROM CART;

DELETE FROM CART
 WHERE MNO = 1
   AND CTYPE = 'pass';

CREATE TABLE ORDER_LIST(
    olno         VARCHAR2(50),
    olprice      NUMBER(7) NOT NULL,
    olfee        NUMBER(4),
    olsale       NUMBER(7) DEFAULT 0,
    oltotal      NUMBER(7) NOT NULL,
    olpayment    VARCHAR2(50) NOT NULL,
    oldate       DATE,
    mno          NUMBER(6),
    
    CONSTRAINT PK_OL PRIMARY KEY(olno),
    CONSTRAINT FK_OL_MEMBER 
        FOREIGN KEY(mno) REFERENCES member(mno) ON DELETE CASCADE
);

ALTER TABLE ORDER_LIST ADD OLDATE DATE; 

ALTER TABLE ORDER_DETAIL DROP CONSTRAINT FK_OD_OL;
ALTER TABLE MEMBER_PASSES DROP CONSTRAINT FK_MP_OL;
ALTER TABLE MEMBER_BOOKS DROP CONSTRAINT FK_MB_OL;

ALTER TABLE ORDER_DETAIL MODIFY OLNO VARCHAR2(50);
ALTER TABLE MEMBER_PASSES MODIFY OLNO VARCHAR2(50);
ALTER TABLE MEMBER_BOOKS MODIFY OLNO VARCHAR2(50);
ALTER TABLE ORDER_LIST MODIFY OLNO VARCHAR2(50);

ALTER TABLE ORDER_DETAIL 
 ADD CONSTRAINT FK_OD_OL 
 FOREIGN KEY (olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE;
ALTER TABLE MEMBER_PASSES 
 ADD CONSTRAINT FK_MP_OL 
 FOREIGN KEY (olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE;
ALTER TABLE MEMBER_BOOKS 
 ADD CONSTRAINT FK_MB_OL 
 FOREIGN KEY (olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE;

-- DELETE FROM ORDER_LIST;
SELECT * FROM ORDER_LIST ORDER BY OLDATE DESC, OLNO DESC;

CREATE TABLE ORDER_DETAIL(
    odno        NUMBER(6),
    odstock     NUMBER(2) NOT NULL,
    odprice     NUMBER(7) NOT NULL,
    odsale      NUMBER(7) DEFAULT 0,
    olno        VARCHAR2(50),
    bno         NUMBER(6),
    pno         NUMBER(6),
    mpno        NUMBER(6),
    
    CONSTRAINT PK_OD PRIMARY KEY(odno),
    CONSTRAINT FK_OD_OL
        FOREIGN KEY(olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE,
    CONSTRAINT FK_OD_BOOK 
        FOREIGN KEY(bno) REFERENCES BOOK(bno) ON DELETE CASCADE,
    CONSTRAINT FK_OD_PASS 
        FOREIGN KEY(pno) REFERENCES PASS(pno) ON DELETE CASCADE,
    CONSTRAINT FK_OD_MP
        FOREIGN KEY(mpno) REFERENCES MEMBER_PASSES(mpno) ON DELETE CASCADE    
);

SELECT * FROM ORDER_DETAIL ORDER BY ODNO DESC;
-- 1786669672181

CREATE TABLE MEMBER_PASSES(
    mpno        NUMBER(6),
    mpcount     NUMBER(3),
    mpstart     DATE DEFAULT SYSDATE,
    mpend       DATE,
    mpstatus    VARCHAR2(15) DEFAULT '사용중',
    mno         NUMBER(6),
    olno        VARCHAR2(50),
    pno         NUMBER(6),
    
    CONSTRAINT PK_MP PRIMARY KEY(mpno),
    CONSTRAINT FK_MP_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_MP_OL 
        FOREIGN KEY(olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE,
    CONSTRAINT FK_MP_PASS 
        FOREIGN KEY(pno) REFERENCES PASS(pno) ON DELETE CASCADE
);

CREATE TABLE MEMBER_BOOKS(
    mbno            NUMBER(6),
    mbstart         DATE NOT NULL,
    mbend           DATE NOT NULL,
    mbreturn        DATE,
    mbextension     NUMBER(2) DEFAULT 0,
    mblatedate      NUMBER(3) DEFAULT 0,
    mblatefee       NUMBER(6) DEFAULT 0,
    mbstatus        VARCHAR2(20) DEFAULT '대여중',
    mno             NUMBER(6),
    olno            VARCHAR2(50),
    bno             NUMBER(6),
    mpno            NUMBER(6),
    
    CONSTRAINT PK_MB PRIMARY KEY(mbno),
    CONSTRAINT FK_MB_MEMBER 
        FOREIGN KEY(mno) REFERENCES MEMBER(mno) ON DELETE CASCADE,
    CONSTRAINT FK_MB_OL
        FOREIGN KEY(olno) REFERENCES ORDER_LIST(olno) ON DELETE CASCADE,
    CONSTRAINT FK_MB_BOOK 
        FOREIGN KEY(bno) REFERENCES BOOK(bno) ON DELETE CASCADE,
    CONSTRAINT FK_MB_MP 
        FOREIGN KEY(mpno) REFERENCES MEMBER_PASSES(mpno) ON DELETE CASCADE
);

SELECT * FROM MEMBER_BOOKS;
SELECT * FROM MEMBER_PASSES;

SELECT * FROM MEMBER;

UPDATE MEMBER_PASSES
   SET MPEND=SYSDATE+1,MPSTATUS='사용중'
 WHERE MPNO=500021;

UPDATE MEMBER_BOOKS
   SET MBSTART = '26/08/10',
       MBEND = '26/08/16',
       MBSTATUS = '대여중'
 WHERE MNO = 82
   AND MBNO = 600067;
   
UPDATE MEMBER_BOOKS
   SET MBSTATUS = '반납완료'
 WHERE MNO = 21
   AND MBNO = 600050;

UPDATE MEMBER_PASSES
   SET MPSTATUS = '만료'
 WHERE MNO = 21
   AND PNO = 900003;

UPDATE MEMBER_PASSES
   SET MPSTATUS = '만료'
 WHERE MNO = 41
   AND PNO = 900001;

-- DELETE FROM MEMBER_BOOKS;
-- DELETE FROM MEMBER_PASSES;

ALTER TABLE MEMBER_BOOKS MODIFY MBSTATUS VARCHAR2(20);

-- 시퀀스
CREATE SEQUENCE MEMBER_SEQ
 START WITH 1
 INCREMENT BY 1;
 
CREATE SEQUENCE QNA_SEQ
 START WITH 10001
 INCREMENT BY 1;

CREATE SEQUENCE AB_SEQ
 START WITH 20001
 INCREMENT BY 1;

CREATE SEQUENCE RATING_SEQ
 START WITH 30001
 INCREMENT BY 1;

CREATE SEQUENCE BOOK_SEQ
 START WITH 100001
 INCREMENT BY 1;
 
CREATE SEQUENCE CART_SEQ
 START WITH 200001
 INCREMENT BY 1;

CREATE SEQUENCE OL_SEQ
 START WITH 300001
 INCREMENT BY 1;

CREATE SEQUENCE OD_SEQ
 START WITH 400001
 INCREMENT BY 1;

CREATE SEQUENCE MP_SEQ
 START WITH 500001
 INCREMENT BY 1;

CREATE SEQUENCE MB_SEQ
 START WITH 600001
 INCREMENT BY 1;

CREATE SEQUENCE PASS_SEQ
 START WITH 900001
 INCREMENT BY 1;
 
 
SELECT SEQUENCE_NAME
  FROM USER_SEQUENCES
 WHERE SEQUENCE_NAME LIKE '%MEMBER%'
    OR SEQUENCE_NAME LIKE '%BOOK%'
    OR SEQUENCE_NAME LIKE '%PASS%'
    OR SEQUENCE_NAME LIKE '%QNA%'
    OR SEQUENCE_NAME LIKE '%AB%'
    OR SEQUENCE_NAME LIKE '%RATING%'
    OR SEQUENCE_NAME LIKE '%CART%'
    OR SEQUENCE_NAME LIKE '%OL%'
    OR SEQUENCE_NAME LIKE '%OD%'
    OR SEQUENCE_NAME LIKE '%MP%'
    OR SEQUENCE_NAME LIKE '%MB%';
    
DESC MEMBER;
DESC BOOK;
DESC PASS;
DESC QNA;
DESC ADMIN_BOARD;
DESC RATING;
DESC CART;
DESC ORDER_LIST;
DESC ORDER_DETAIL;
DESC MEMBER_PASSES;
DESC MEMBER_BOOKS;
    